version: '3'
services:
  app:
    container_name: docker_group1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - docker-network
    volumes:
      - docker-vol:/app

volumes:
  docker-vol:

networks:
  docker-network:
  